pyspice_lib = {'A': {'ALIAS': 'A',
       'PREFIX': 'A',
       'add': 'add_xspice_to_circuit2',
       'model': None,
       'pin_names_map': {'*': '*'},
       'pins_map': {0: '*'}},
 'AcLine': {'ALIAS': 'V',
            'PREFIX': 'V',
            'add': 'add_part_to_circuit2',
            'dc_value': 'dc_value',
            'pin_names_map': {'n': 'minus', 'p': 'plus'},
            'pins_map': {0: 'plus', 1: 'minus'},
            'value': 'dc_value'},
 'AmplitudeModulatedCurrentSource': {'ALIAS': 'I',
                                     'PREFIX': 'I',
                                     'add': 'add_part_to_circuit2',
                                     'dc_value': 'dc_value',
                                     'pin_names_map': {'n': 'minus',
                                                       'p': 'plus'},
                                     'pins_map': {0: 'plus', 1: 'minus'},
                                     'value': 'dc_value'},
 'AmplitudeModulatedVoltageSource': {'ALIAS': 'V',
                                     'PREFIX': 'V',
                                     'add': 'add_part_to_circuit2',
                                     'dc_value': 'dc_value',
                                     'pin_names_map': {'n': 'minus',
                                                       'p': 'plus'},
                                     'pins_map': {0: 'plus', 1: 'minus'},
                                     'value': 'dc_value'},
 'B': {'ALIAS': 'B',
       'PREFIX': 'B',
       'add': 'add_part_to_circuit2',
       'current_expression': None,
       'device_temperature': None,
       'pin_names_map': {'n': 'minus', 'p': 'plus'},
       'pins_map': {0: 'plus', 1: 'minus'},
       'tc1': None,
       'tc2': None,
       'temperature': None,
       'voltage_expression': None},
 'BJT': {'ALIAS': 'Q',
         'LONG_ALIAS': 'BJT',
         'PREFIX': 'Q',
         'add': 'add_part_to_circuit2',
         'area': None,
         'areab': None,
         'areac': None,
         'device_temperature': None,
         'ic': None,
         'model': None,
         'multiplier': None,
         'off': False,
         'pin_names_map': {'b': 'base',
                           'c': 'collector',
                           'e': 'emitter',
                           'substrate': 'substrate'},
         'pins_map': {0: 'collector', 1: 'base', 2: 'emitter', 3: 'substrate'},
         'temperature': None},
 'BehavioralCapacitor': {'ALIAS': 'BehavioralCapacitor',
                         'PREFIX': 'C',
                         'add': 'add_part_to_circuit2',
                         'capacitance_expression': None,
                         'pin_names_map': {'n': 'minus', 'p': 'plus'},
                         'pins_map': {0: 'plus', 1: 'minus'},
                         'tc1': None,
                         'tc2': None},
 'BehavioralInductor': {'ALIAS': 'BehavioralInductor',
                        'PREFIX': 'L',
                        'add': 'add_part_to_circuit2',
                        'inductance_expression': None,
                        'pin_names_map': {'n': 'minus', 'p': 'plus'},
                        'pins_map': {0: 'plus', 1: 'minus'},
                        'tc1': None,
                        'tc2': None},
 'BehavioralResistor': {'ALIAS': 'BehavioralResistor',
                        'PREFIX': 'R',
                        'add': 'add_part_to_circuit2',
                        'pin_names_map': {'n': 'minus', 'p': 'plus'},
                        'pins_map': {0: 'plus', 1: 'minus'},
                        'resistance_expression': None,
                        'tc1': None,
                        'tc2': None},
 'BehavioralSource': {'ALIAS': 'B',
                      'PREFIX': 'B',
                      'add': 'add_part_to_circuit2',
                      'current_expression': None,
                      'device_temperature': None,
                      'pin_names_map': {'n': 'minus', 'p': 'plus'},
                      'pins_map': {0: 'plus', 1: 'minus'},
                      'tc1': None,
                      'tc2': None,
                      'temperature': None,
                      'voltage_expression': None},
 'BipolarJunctionTransistor': {'ALIAS': 'Q',
                               'LONG_ALIAS': 'BJT',
                               'PREFIX': 'Q',
                               'add': 'add_part_to_circuit2',
                               'area': None,
                               'areab': None,
                               'areac': None,
                               'device_temperature': None,
                               'ic': None,
                               'model': None,
                               'multiplier': None,
                               'off': False,
                               'pin_names_map': {'b': 'base',
                                                 'c': 'collector',
                                                 'e': 'emitter',
                                                 'substrate': 'substrate'},
                               'pins_map': {0: 'collector',
                                            1: 'base',
                                            2: 'emitter',
                                            3: 'substrate'},
                               'temperature': None},
 'C': {'ALIAS': 'C',
       'PREFIX': 'C',
       'add': 'add_part_to_circuit2',
       'capacitance': 'capacitance',
       'device_temperature': None,
       'initial_condition': None,
       'model': None,
       'multiplier': None,
       'pin_names_map': {'n': 'minus', 'p': 'plus'},
       'pins_map': {0: 'plus', 1: 'minus'},
       'scale': None,
       'temperature': None,
       'value': 'capacitance'},
 'CCCS': {'ALIAS': 'F',
          'LONG_ALIAS': 'CCCS',
          'PREFIX': 'F',
          'add': 'add_part_to_circuit2',
          'current_gain': None,
          'multiplier': None,
          'pin_names_map': {'n': 'minus', 'p': 'plus'},
          'pins_map': {0: 'plus', 1: 'minus'},
          'source': None},
 'CCS': {'ALIAS': 'W',
         'LONG_ALIAS': 'CCS',
         'PREFIX': 'W',
         'add': 'add_part_to_circuit2',
         'initial_state': None,
         'model': None,
         'pin_names_map': {'n': 'minus', 'p': 'plus'},
         'pins_map': {0: 'plus', 1: 'minus'},
         'source': None},
 'CCVS': {'ALIAS': 'H',
          'LONG_ALIAS': 'CCVS',
          'PREFIX': 'H',
          'add': 'add_part_to_circuit2',
          'pin_names_map': {'n': 'minus', 'p': 'plus'},
          'pins_map': {0: 'plus', 1: 'minus'},
          'source': None,
          'transresistance': None},
 'Capacitor': {'ALIAS': 'C',
               'PREFIX': 'C',
               'add': 'add_part_to_circuit2',
               'capacitance': 'capacitance',
               'device_temperature': None,
               'initial_condition': None,
               'model': None,
               'multiplier': None,
               'pin_names_map': {'n': 'minus', 'p': 'plus'},
               'pins_map': {0: 'plus', 1: 'minus'},
               'scale': None,
               'temperature': None,
               'value': 'capacitance'},
 'CoupledInductor': {'ALIAS': 'K',
                     'PREFIX': 'K',
                     'add': 'add_part_to_circuit2',
                     'coupling_factor': None,
                     'inductor1': None,
                     'inductor2': None,
                     'pin_names_map': {},
                     'pins_map': {}},
 'CoupledMulticonductorLine': {'ALIAS': 'P',
                               'PREFIX': 'P',
                               'add': 'add_part_to_circuit2',
                               'length': None,
                               'model': None,
                               'pin_names_map': {'*': '*'},
                               'pins_map': {0: '*'}},
 'CurrentControlledCurrentSource': {'ALIAS': 'F',
                                    'LONG_ALIAS': 'CCCS',
                                    'PREFIX': 'F',
                                    'add': 'add_part_to_circuit2',
                                    'current_gain': None,
                                    'multiplier': None,
                                    'pin_names_map': {'n': 'minus',
                                                      'p': 'plus'},
                                    'pins_map': {0: 'plus', 1: 'minus'},
                                    'source': None},
 'CurrentControlledSwitch': {'ALIAS': 'W',
                             'LONG_ALIAS': 'CCS',
                             'PREFIX': 'W',
                             'add': 'add_part_to_circuit2',
                             'initial_state': None,
                             'model': None,
                             'pin_names_map': {'n': 'minus', 'p': 'plus'},
                             'pins_map': {0: 'plus', 1: 'minus'},
                             'source': None},
 'CurrentControlledVoltageSource': {'ALIAS': 'H',
                                    'LONG_ALIAS': 'CCVS',
                                    'PREFIX': 'H',
                                    'add': 'add_part_to_circuit2',
                                    'pin_names_map': {'n': 'minus',
                                                      'p': 'plus'},
                                    'pins_map': {0: 'plus', 1: 'minus'},
                                    'source': None,
                                    'transresistance': None},
 'CurrentSource': {'ALIAS': 'I',
                   'PREFIX': 'I',
                   'add': 'add_part_to_circuit2',
                   'dc_value': 'dc_value',
                   'pin_names_map': {'n': 'minus', 'p': 'plus'},
                   'pins_map': {0: 'plus', 1: 'minus'},
                   'value': 'dc_value'},
 'D': {'ALIAS': 'D',
       'PREFIX': 'D',
       'add': 'add_part_to_circuit2',
       'area': None,
       'device_temperature': None,
       'ic': None,
       'model': None,
       'multiplier': None,
       'off': False,
       'pin_names_map': {'a': 'anode', 'c': 'cathode'},
       'pins_map': {0: 'cathode', 1: 'anode'},
       'pj': None,
       'temperature': None},
 'Diode': {'ALIAS': 'D',
           'PREFIX': 'D',
           'add': 'add_part_to_circuit2',
           'area': None,
           'device_temperature': None,
           'ic': None,
           'model': None,
           'multiplier': None,
           'off': False,
           'pin_names_map': {'a': 'anode', 'c': 'cathode'},
           'pins_map': {0: 'cathode', 1: 'anode'},
           'pj': None,
           'temperature': None},
 'ExponentialCurrentSource': {'ALIAS': 'I',
                              'PREFIX': 'I',
                              'add': 'add_part_to_circuit2',
                              'dc_value': 'dc_value',
                              'pin_names_map': {'n': 'minus', 'p': 'plus'},
                              'pins_map': {0: 'plus', 1: 'minus'},
                              'value': 'dc_value'},
 'ExponentialVoltageSource': {'ALIAS': 'V',
                              'PREFIX': 'V',
                              'add': 'add_part_to_circuit2',
                              'dc_value': 'dc_value',
                              'pin_names_map': {'n': 'minus', 'p': 'plus'},
                              'pins_map': {0: 'plus', 1: 'minus'},
                              'value': 'dc_value'},
 'F': {'ALIAS': 'F',
       'LONG_ALIAS': 'CCCS',
       'PREFIX': 'F',
       'add': 'add_part_to_circuit2',
       'current_gain': None,
       'multiplier': None,
       'pin_names_map': {'n': 'minus', 'p': 'plus'},
       'pins_map': {0: 'plus', 1: 'minus'},
       'source': None},
 'GSSElement': {'ALIAS': 'N',
                'PREFIX': 'N',
                'add': 'add_part_to_circuit2',
                'pin_names_map': {'*': '*'},
                'pins_map': {0: '*'}},
 'H': {'ALIAS': 'H',
       'LONG_ALIAS': 'CCVS',
       'PREFIX': 'H',
       'add': 'add_part_to_circuit2',
       'pin_names_map': {'n': 'minus', 'p': 'plus'},
       'pins_map': {0: 'plus', 1: 'minus'},
       'source': None,
       'transresistance': None},
 'I': {'ALIAS': 'I',
       'PREFIX': 'I',
       'add': 'add_part_to_circuit2',
       'dc_value': 'dc_value',
       'pin_names_map': {'n': 'minus', 'p': 'plus'},
       'pins_map': {0: 'plus', 1: 'minus'},
       'value': 'dc_value'},
 'Inductor': {'ALIAS': 'L',
              'PREFIX': 'L',
              'add': 'add_part_to_circuit2',
              'device_temperature': None,
              'inductance': 'inductance',
              'initial_condition': None,
              'model': None,
              'multiplier': None,
              'nt': None,
              'pin_names_map': {'n': 'minus', 'p': 'plus'},
              'pins_map': {0: 'plus', 1: 'minus'},
              'scale': None,
              'temperature': None,
              'value': 'inductance'},
 'J': {'ALIAS': 'J',
       'LONG_ALIAS': 'JFET',
       'PREFIX': 'J',
       'add': 'add_part_to_circuit2',
       'area': None,
       'ic': None,
       'model': None,
       'multiplier': None,
       'off': False,
       'pin_names_map': {'d': 'drain', 'g': 'gate', 's': 'source'},
       'pins_map': {0: 'drain', 1: 'gate', 2: 'source'},
       'temperature': None},
 'JFET': {'ALIAS': 'J',
          'LONG_ALIAS': 'JFET',
          'PREFIX': 'J',
          'add': 'add_part_to_circuit2',
          'area': None,
          'ic': None,
          'model': None,
          'multiplier': None,
          'off': False,
          'pin_names_map': {'d': 'drain', 'g': 'gate', 's': 'source'},
          'pins_map': {0: 'drain', 1: 'gate', 2: 'source'},
          'temperature': None},
 'JunctionFieldEffectTransistor': {'ALIAS': 'J',
                                   'LONG_ALIAS': 'JFET',
                                   'PREFIX': 'J',
                                   'add': 'add_part_to_circuit2',
                                   'area': None,
                                   'ic': None,
                                   'model': None,
                                   'multiplier': None,
                                   'off': False,
                                   'pin_names_map': {'d': 'drain',
                                                     'g': 'gate',
                                                     's': 'source'},
                                   'pins_map': {0: 'drain',
                                                1: 'gate',
                                                2: 'source'},
                                   'temperature': None},
 'K': {'ALIAS': 'K',
       'PREFIX': 'K',
       'add': 'add_part_to_circuit2',
       'coupling_factor': None,
       'inductor1': None,
       'inductor2': None,
       'pin_names_map': {},
       'pins_map': {}},
 'L': {'ALIAS': 'L',
       'PREFIX': 'L',
       'add': 'add_part_to_circuit2',
       'device_temperature': None,
       'inductance': 'inductance',
       'initial_condition': None,
       'model': None,
       'multiplier': None,
       'nt': None,
       'pin_names_map': {'n': 'minus', 'p': 'plus'},
       'pins_map': {0: 'plus', 1: 'minus'},
       'scale': None,
       'temperature': None,
       'value': 'inductance'},
 'LosslessTransmissionLine': {'ALIAS': 'TransmissionLine',
                              'PREFIX': 'T',
                              'add': 'add_part_to_circuit2',
                              'frequency': None,
                              'impedance': 50,
                              'normalized_length': None,
                              'pin_names_map': {'i': 'input_minus',
                                                'o': 'output_minus'},
                              'pins_map': {0: 'output_plus',
                                           1: 'output_minus',
                                           2: 'input_plus',
                                           3: 'input_minus'},
                              'time_delay': None},
 'LossyTransmission': {'ALIAS': 'O',
                       'PREFIX': 'O',
                       'add': 'add_part_to_circuit2',
                       'model': None,
                       'pin_names_map': {'i': 'input_minus',
                                         'o': 'output_minus'},
                       'pins_map': {0: 'output_plus',
                                    1: 'output_minus',
                                    2: 'input_plus',
                                    3: 'input_minus'}},
 'M': {'ALIAS': 'M',
       'LONG_ALIAS': 'MOSFET',
       'PREFIX': 'M',
       'add': 'add_part_to_circuit2',
       'drain_area': None,
       'drain_number_square': None,
       'drain_perimeter': None,
       'ic': None,
       'length': None,
       'model': None,
       'multiplier': None,
       'nfin': None,
       'off': False,
       'pin_names_map': {'b': 'bulk', 'd': 'drain', 'g': 'gate', 's': 'source'},
       'pins_map': {0: 'drain', 1: 'gate', 2: 'source', 3: 'bulk'},
       'source_area': None,
       'source_number_square': None,
       'source_perimeter': None,
       'temperature': None,
       'width': None},
 'MESFET': {'ALIAS': 'Z',
            'LONG_ALIAS': 'MESFET',
            'PREFIX': 'Z',
            'add': 'add_part_to_circuit2',
            'area': None,
            'ic': None,
            'model': None,
            'multiplier': None,
            'off': False,
            'pin_names_map': {'d': 'drain', 'g': 'gate', 's': 'source'},
            'pins_map': {0: 'drain', 1: 'gate', 2: 'source'}},
 'MOSFET': {'ALIAS': 'M',
            'LONG_ALIAS': 'MOSFET',
            'PREFIX': 'M',
            'add': 'add_part_to_circuit2',
            'drain_area': None,
            'drain_number_square': None,
            'drain_perimeter': None,
            'ic': None,
            'length': None,
            'model': None,
            'multiplier': None,
            'nfin': None,
            'off': False,
            'pin_names_map': {'b': 'bulk',
                              'd': 'drain',
                              'g': 'gate',
                              's': 'source'},
            'pins_map': {0: 'drain', 1: 'gate', 2: 'source', 3: 'bulk'},
            'source_area': None,
            'source_number_square': None,
            'source_perimeter': None,
            'temperature': None,
            'width': None},
 'Mesfet': {'ALIAS': 'Z',
            'LONG_ALIAS': 'MESFET',
            'PREFIX': 'Z',
            'add': 'add_part_to_circuit2',
            'area': None,
            'ic': None,
            'model': None,
            'multiplier': None,
            'off': False,
            'pin_names_map': {'d': 'drain', 'g': 'gate', 's': 'source'},
            'pins_map': {0: 'drain', 1: 'gate', 2: 'source'}},
 'Mosfet': {'ALIAS': 'M',
            'LONG_ALIAS': 'MOSFET',
            'PREFIX': 'M',
            'add': 'add_part_to_circuit2',
            'drain_area': None,
            'drain_number_square': None,
            'drain_perimeter': None,
            'ic': None,
            'length': None,
            'model': None,
            'multiplier': None,
            'nfin': None,
            'off': False,
            'pin_names_map': {'b': 'bulk',
                              'd': 'drain',
                              'g': 'gate',
                              's': 'source'},
            'pins_map': {0: 'drain', 1: 'gate', 2: 'source', 3: 'bulk'},
            'source_area': None,
            'source_number_square': None,
            'source_perimeter': None,
            'temperature': None,
            'width': None},
 'N': {'ALIAS': 'N',
       'PREFIX': 'N',
       'add': 'add_part_to_circuit2',
       'pin_names_map': {'*': '*'},
       'pins_map': {0: '*'}},
 'NonLinearCurrentSource': {'ALIAS': 'NonLinearCurrentSource',
                            'PREFIX': 'G',
                            'add': 'add_part_to_circuit2',
                            'pin_names_map': {'n': 'minus', 'p': 'plus'},
                            'pins_map': {0: 'plus', 1: 'minus'},
                            'transconductance': None},
 'NonLinearVoltageSource': {'ALIAS': 'NonLinearVoltageSource',
                            'PREFIX': 'E',
                            'VALID_KWARGS': ('expression', 'table'),
                            'add': 'add_part_to_circuit2',
                            'pin_names_map': {'n': 'minus', 'p': 'plus'},
                            'pins_map': {0: 'plus', 1: 'minus'}},
 'O': {'ALIAS': 'O',
       'PREFIX': 'O',
       'add': 'add_part_to_circuit2',
       'model': None,
       'pin_names_map': {'i': 'input_minus', 'o': 'output_minus'},
       'pins_map': {0: 'output_plus',
                    1: 'output_minus',
                    2: 'input_plus',
                    3: 'input_minus'}},
 'P': {'ALIAS': 'P',
       'PREFIX': 'P',
       'add': 'add_part_to_circuit2',
       'length': None,
       'model': None,
       'pin_names_map': {'*': '*'},
       'pins_map': {0: '*'}},
 'PieceWiseLinearCurrentSource': {'ALIAS': 'I',
                                  'PREFIX': 'I',
                                  'add': 'add_part_to_circuit2',
                                  'dc_value': 'dc_value',
                                  'pin_names_map': {'n': 'minus', 'p': 'plus'},
                                  'pins_map': {0: 'plus', 1: 'minus'},
                                  'value': 'dc_value'},
 'PieceWiseLinearVoltageSource': {'ALIAS': 'V',
                                  'PREFIX': 'V',
                                  'add': 'add_part_to_circuit2',
                                  'dc_value': 'dc_value',
                                  'pin_names_map': {'n': 'minus', 'p': 'plus'},
                                  'pins_map': {0: 'plus', 1: 'minus'},
                                  'value': 'dc_value'},
 'PulseCurrentSource': {'ALIAS': 'I',
                        'PREFIX': 'I',
                        'add': 'add_part_to_circuit2',
                        'dc_value': 'dc_value',
                        'pin_names_map': {'n': 'minus', 'p': 'plus'},
                        'pins_map': {0: 'plus', 1: 'minus'},
                        'value': 'dc_value'},
 'PulseVoltageSource': {'ALIAS': 'V',
                        'PREFIX': 'V',
                        'add': 'add_part_to_circuit2',
                        'dc_value': 'dc_value',
                        'pin_names_map': {'n': 'minus', 'p': 'plus'},
                        'pins_map': {0: 'plus', 1: 'minus'},
                        'value': 'dc_value'},
 'Q': {'ALIAS': 'Q',
       'LONG_ALIAS': 'BJT',
       'PREFIX': 'Q',
       'add': 'add_part_to_circuit2',
       'area': None,
       'areab': None,
       'areac': None,
       'device_temperature': None,
       'ic': None,
       'model': None,
       'multiplier': None,
       'off': False,
       'pin_names_map': {'b': 'base',
                         'c': 'collector',
                         'e': 'emitter',
                         'substrate': 'substrate'},
       'pins_map': {0: 'collector', 1: 'base', 2: 'emitter', 3: 'substrate'},
       'temperature': None},
 'R': {'ALIAS': 'R',
       'PREFIX': 'R',
       'ac': None,
       'add': 'add_part_to_circuit2',
       'device_temperature': None,
       'multiplier': None,
       'noisy': None,
       'pin_names_map': {'n': 'minus', 'p': 'plus'},
       'pins_map': {0: 'plus', 1: 'minus'},
       'resistance': 'resistance',
       'scale': None,
       'temperature': None,
       'value': 'resistance'},
 'RandomCurrentSource': {'ALIAS': 'I',
                         'PREFIX': 'I',
                         'add': 'add_part_to_circuit2',
                         'dc_value': 'dc_value',
                         'pin_names_map': {'n': 'minus', 'p': 'plus'},
                         'pins_map': {0: 'plus', 1: 'minus'},
                         'value': 'dc_value'},
 'RandomVoltageSource': {'ALIAS': 'V',
                         'PREFIX': 'V',
                         'add': 'add_part_to_circuit2',
                         'dc_value': 'dc_value',
                         'pin_names_map': {'n': 'minus', 'p': 'plus'},
                         'pins_map': {0: 'plus', 1: 'minus'},
                         'value': 'dc_value'},
 'Resistor': {'ALIAS': 'R',
              'PREFIX': 'R',
              'ac': None,
              'add': 'add_part_to_circuit2',
              'device_temperature': None,
              'multiplier': None,
              'noisy': None,
              'pin_names_map': {'n': 'minus', 'p': 'plus'},
              'pins_map': {0: 'plus', 1: 'minus'},
              'resistance': 'resistance',
              'scale': None,
              'temperature': None,
              'value': 'resistance'},
 'S': {'ALIAS': 'S',
       'LONG_ALIAS': 'VCS',
       'PREFIX': 'S',
       'add': 'add_part_to_circuit2',
       'initial_state': None,
       'model': None,
       'pin_names_map': {'i': 'input_minus', 'o': 'output_minus'},
       'pins_map': {0: 'output_plus',
                    1: 'output_minus',
                    2: 'input_plus',
                    3: 'input_minus'}},
 'SemiconductorCapacitor': {'ALIAS': 'SemiconductorCapacitor',
                            'PREFIX': 'C',
                            'add': 'add_part_to_circuit2',
                            'capacitance': 'capacitance',
                            'device_temperature': None,
                            'initial_condition': None,
                            'length': None,
                            'model': None,
                            'multiplier': None,
                            'pin_names_map': {'n': 'minus', 'p': 'plus'},
                            'pins_map': {0: 'plus', 1: 'minus'},
                            'scale': None,
                            'temperature': None,
                            'value': 'capacitance',
                            'width': None},
 'SemiconductorResistor': {'ALIAS': 'SemiconductorResistor',
                           'PREFIX': 'R',
                           'ac': None,
                           'add': 'add_part_to_circuit2',
                           'device_temperature': None,
                           'length': None,
                           'model': None,
                           'multiplier': None,
                           'noisy': None,
                           'pin_names_map': {'n': 'minus', 'p': 'plus'},
                           'pins_map': {0: 'plus', 1: 'minus'},
                           'resistance': 'resistance',
                           'scale': None,
                           'temperature': None,
                           'value': 'resistance',
                           'width': None},
 'SingleFrequencyFMCurrentSource': {'ALIAS': 'I',
                                    'PREFIX': 'I',
                                    'add': 'add_part_to_circuit2',
                                    'dc_value': 'dc_value',
                                    'pin_names_map': {'n': 'minus',
                                                      'p': 'plus'},
                                    'pins_map': {0: 'plus', 1: 'minus'},
                                    'value': 'dc_value'},
 'SingleFrequencyFMVoltageSource': {'ALIAS': 'V',
                                    'PREFIX': 'V',
                                    'add': 'add_part_to_circuit2',
                                    'dc_value': 'dc_value',
                                    'pin_names_map': {'n': 'minus',
                                                      'p': 'plus'},
                                    'pins_map': {0: 'plus', 1: 'minus'},
                                    'value': 'dc_value'},
 'SingleLossyTransmissionLine': {'ALIAS': 'Y',
                                 'PREFIX': 'Y',
                                 'add': 'add_part_to_circuit2',
                                 'length': None,
                                 'model': None,
                                 'pin_names_map': {'i': 'input_minus',
                                                   'o': 'output_minus'},
                                 'pins_map': {0: 'output_plus',
                                              1: 'output_minus',
                                              2: 'input_plus',
                                              3: 'input_minus'}},
 'SinusoidalCurrentSource': {'ALIAS': 'I',
                             'PREFIX': 'I',
                             'add': 'add_part_to_circuit2',
                             'dc_value': 'dc_value',
                             'pin_names_map': {'n': 'minus', 'p': 'plus'},
                             'pins_map': {0: 'plus', 1: 'minus'},
                             'value': 'dc_value'},
 'SinusoidalVoltageSource': {'ALIAS': 'V',
                             'PREFIX': 'V',
                             'add': 'add_part_to_circuit2',
                             'dc_value': 'dc_value',
                             'pin_names_map': {'n': 'minus', 'p': 'plus'},
                             'pins_map': {0: 'plus', 1: 'minus'},
                             'value': 'dc_value'},
 'SubCircuitElement': {'ALIAS': 'X',
                       'PREFIX': 'X',
                       'add': 'add_part_to_circuit2',
                       'pin_names_map': {'*': '*'},
                       'pins_map': {0: '*'},
                       'subcircuit_name': None},
 'TransmissionLine': {'ALIAS': 'TransmissionLine',
                      'PREFIX': 'T',
                      'add': 'add_part_to_circuit2',
                      'frequency': None,
                      'impedance': 50,
                      'normalized_length': None,
                      'pin_names_map': {'i': 'input_minus',
                                        'o': 'output_minus'},
                      'pins_map': {0: 'output_plus',
                                   1: 'output_minus',
                                   2: 'input_plus',
                                   3: 'input_minus'},
                      'time_delay': None},
 'U': {'ALIAS': 'U',
       'PREFIX': 'U',
       'add': 'add_part_to_circuit2',
       'length': None,
       'model': None,
       'number_of_lumps': None,
       'pin_names_map': {'capacitance_node': 'capacitance_node',
                         'i': 'input',
                         'o': 'output'},
       'pins_map': {0: 'output', 1: 'input', 2: 'capacitance_node'}},
 'UniformDistributedRCLine': {'ALIAS': 'U',
                              'PREFIX': 'U',
                              'add': 'add_part_to_circuit2',
                              'length': None,
                              'model': None,
                              'number_of_lumps': None,
                              'pin_names_map': {'capacitance_node': 'capacitance_node',
                                                'i': 'input',
                                                'o': 'output'},
                              'pins_map': {0: 'output',
                                           1: 'input',
                                           2: 'capacitance_node'}},
 'V': {'ALIAS': 'V',
       'PREFIX': 'V',
       'add': 'add_part_to_circuit2',
       'dc_value': 'dc_value',
       'pin_names_map': {'n': 'minus', 'p': 'plus'},
       'pins_map': {0: 'plus', 1: 'minus'},
       'value': 'dc_value'},
 'VCCS': {'ALIAS': 'VCCS',
          'PREFIX': 'G',
          'add': 'add_part_to_circuit2',
          'multiplier': None,
          'pin_names_map': {'i': 'input_minus', 'o': 'output_minus'},
          'pins_map': {0: 'output_plus',
                       1: 'output_minus',
                       2: 'input_plus',
                       3: 'input_minus'},
          'transconductance': None},
 'VCS': {'ALIAS': 'S',
         'LONG_ALIAS': 'VCS',
         'PREFIX': 'S',
         'add': 'add_part_to_circuit2',
         'initial_state': None,
         'model': None,
         'pin_names_map': {'i': 'input_minus', 'o': 'output_minus'},
         'pins_map': {0: 'output_plus',
                      1: 'output_minus',
                      2: 'input_plus',
                      3: 'input_minus'}},
 'VCVS': {'ALIAS': 'VCVS',
          'PREFIX': 'E',
          'add': 'add_part_to_circuit2',
          'pin_names_map': {'i': 'input_minus', 'o': 'output_minus'},
          'pins_map': {0: 'output_plus',
                       1: 'output_minus',
                       2: 'input_plus',
                       3: 'input_minus'},
          'voltage_gain': None},
 'VoltageControlledCurrentSource': {'ALIAS': 'VCCS',
                                    'PREFIX': 'G',
                                    'add': 'add_part_to_circuit2',
                                    'multiplier': None,
                                    'pin_names_map': {'i': 'input_minus',
                                                      'o': 'output_minus'},
                                    'pins_map': {0: 'output_plus',
                                                 1: 'output_minus',
                                                 2: 'input_plus',
                                                 3: 'input_minus'},
                                    'transconductance': None},
 'VoltageControlledSwitch': {'ALIAS': 'S',
                             'LONG_ALIAS': 'VCS',
                             'PREFIX': 'S',
                             'add': 'add_part_to_circuit2',
                             'initial_state': None,
                             'model': None,
                             'pin_names_map': {'i': 'input_minus',
                                               'o': 'output_minus'},
                             'pins_map': {0: 'output_plus',
                                          1: 'output_minus',
                                          2: 'input_plus',
                                          3: 'input_minus'}},
 'VoltageControlledVoltageSource': {'ALIAS': 'VCVS',
                                    'PREFIX': 'E',
                                    'add': 'add_part_to_circuit2',
                                    'pin_names_map': {'i': 'input_minus',
                                                      'o': 'output_minus'},
                                    'pins_map': {0: 'output_plus',
                                                 1: 'output_minus',
                                                 2: 'input_plus',
                                                 3: 'input_minus'},
                                    'voltage_gain': None},
 'VoltageSource': {'ALIAS': 'V',
                   'PREFIX': 'V',
                   'add': 'add_part_to_circuit2',
                   'dc_value': 'dc_value',
                   'pin_names_map': {'n': 'minus', 'p': 'plus'},
                   'pins_map': {0: 'plus', 1: 'minus'},
                   'value': 'dc_value'},
 'W': {'ALIAS': 'W',
       'LONG_ALIAS': 'CCS',
       'PREFIX': 'W',
       'add': 'add_part_to_circuit2',
       'initial_state': None,
       'model': None,
       'pin_names_map': {'n': 'minus', 'p': 'plus'},
       'pins_map': {0: 'plus', 1: 'minus'},
       'source': None},
 'X': {'ALIAS': 'X',
       'PREFIX': 'X',
       'add': 'add_part_to_circuit2',
       'pin_names_map': {'*': '*'},
       'pins_map': {0: '*'},
       'subcircuit_name': None},
 'XSpiceElement': {'ALIAS': 'A',
                   'PREFIX': 'A',
                   'add': 'add_part_to_circuit2',
                   'model': None,
                   'pin_names_map': {'*': '*'},
                   'pins_map': {0: '*'}},
 'Y': {'ALIAS': 'Y',
       'PREFIX': 'Y',
       'add': 'add_part_to_circuit2',
       'length': None,
       'model': None,
       'pin_names_map': {'i': 'input_minus', 'o': 'output_minus'},
       'pins_map': {0: 'output_plus',
                    1: 'output_minus',
                    2: 'input_plus',
                    3: 'input_minus'}},
 'Z': {'ALIAS': 'Z',
       'LONG_ALIAS': 'MESFET',
       'PREFIX': 'Z',
       'add': 'add_part_to_circuit2',
       'area': None,
       'ic': None,
       'model': None,
       'multiplier': None,
       'off': False,
       'pin_names_map': {'d': 'drain', 'g': 'gate', 's': 'source'},
       'pins_map': {0: 'drain', 1: 'gate', 2: 'source'}}}
